### ISSUE TITLE
Using WebView from more than one process at once with the same data directory is not supported.

### ISSUE THREAD

**Issue by vladislav-t** [appmetrica/appmetrica-sdk-android#9]
### 📚 AppMetrica SDK Version

6.5.0

### 📝 Description

I have using Firebase sdk, my init code is: 
            FirebaseApp.initializeApp(this);
            initYandexMetrica(getApplicationContext(), this);
, and looks like crash starts when I update targetSdk to 34.

### 🔍 Reproducing the issue

1. Open app
2. Wait 4 seconds
3. Crash!

### 📋 Relevant AppMetrica Log Output or Crash Logs

--------- beginning of crash
2024-07-30 11:03:20.282 14819-14819 AndroidRuntime          pid-14819                            E  FATAL EXCEPTION: main
                                                                                                    Process: photo.frames.collage.editor:AppMetrica, PID: 14819
                                                                                                    java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process photo.frames.collage.editor:AppMetrica (pid 14819), lock owner  unknown
                                                                                                    	at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle6432.aab-stable-647818633:201)
                                                                                                    	at org.chromium.android_webview.AwBrowserProcess.j(chromium-TrichromeWebViewGoogle6432.aab-stable-647818633:16)
                                                                                                    	at com.android.webview.chromium.M.e(chromium-TrichromeWebViewGoogle6432.aab-stable-647818633:203)
                                                                                                    	at WV.AY.run(chromium-TrichromeWebViewGoogle6432.aab-stable-647818633:11)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

### 📦 Dependencies

    implementation 'com.yandex.android:mobileads:7.2.0'
    implementation 'io.appmetrica.analytics:analytics:6.5.0'
    
    implementation 'com.google.android.gms:play-services-ads:23.2.0'

**Comment by vladislav-t** [comment]
After research I found that the bug is caused by another ad provider that can't be init on AppMetrica process, so after I check main process is works well.
